name: CI

on: [push]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Cache Composer dependencies
              uses: actions/cache@v2
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            - name: Install dependencies
              uses: php-actions/composer@v6
              with:
                  php_version: '8.1'

            - name: Run Coding Standards
              uses: php-actions/composer@v6
              with:
                  command: cs
                  php_extensions: intl

            - name: Run Static Analysis
              uses: php-actions/composer@v6
              with:
                  command: static

            - name: Run PHPUnit
              uses: php-actions/composer@v6
              with:
                  command: test
